from rpg_battle.battle_action_goblin0_ren import GOBLIN_ACTION_LIBRARY
from rpg_battle.battle_action_huge0_ren import HUGE_ACTION_LIBRARY0
from rpg_battle.battle_action_love0_ren import LOVE_ACTION_LIBRARY0
from rpg_battle.battle_action_machine_ren import MACHINE_ACTION_LIBRARY
from rpg_battle.battle_action_yuri0_ren import YURI_ACTION_LIBRARY0

from rpg_battle.battle_actions_self0_ren import MASTURBATION_ACTION_LIBRARY

"""renpy
init -90 python:
"""
THEME_SELF_LIBRARY = MASTURBATION_ACTION_LIBRARY
THEME_LOVE_LIBRARY = LOVE_ACTION_LIBRARY0
THEME_HUGE_LIBRARY = HUGE_ACTION_LIBRARY0
THEME_MACHINE_LIBRARY = MACHINE_ACTION_LIBRARY
THEME_GOBLIN_LIBRARY = GOBLIN_ACTION_LIBRARY
THEME_YURI_LIBRARY = YURI_ACTION_LIBRARY0
